//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#include "cocos2d.h"
#include "Box2D/Box2D.h"

USING_NS_CC;

class LHSprite;
class LHAnimationNode : public CCObject
{
    CCString* uniqueName;

    bool loop;
    float speed;
    int repetitions;
    bool startAtLaunch;

	CCArray* frames;
    
    CCSpriteBatchNode* batchNode; //week ptr

public:
	~LHAnimationNode();
	LHAnimationNode(CCString * name);
	////////////////////////////////////////////////////////////////////////////////
	void setUniqueName(CCString* name);
	CCString* getUniqueName();

	void setLoop(bool bLoop) { loop = bLoop; }
	bool getLoop() {return loop;}

	void setRepetitions(int nRep) { repetitions = nRep; }
	int getRepetitions() { return repetitions; }

	void setStartAtLaunch(bool bstart) { startAtLaunch = bstart; }
	bool getStartAtLaunch() { return startAtLaunch; }

	void setSpeed(float sp) { speed = sp; }
	float getSpeed() { return speed; }

	void setFrames(CCArray* frames);
	void setBatchNode(CCSpriteBatchNode* node);

	int getNumberOfFrames();

	void runAnimationOnSprite(LHSprite* ccsprite,CCNode *animNotifierId,SEL_CallFuncND animNotifierSel,bool notifOnLoop);

	void setAnimationTexturePropertiesOnSprite(LHSprite* ccsprite);
	void setFrame(int frameNo,LHSprite* spr);
};